add_requires("vulkansdk")
add_requires("volk")
add_requires("vulkan-memory-allocator")
add_requires("glfw")
add_requires("fastgltf")

target("Lettuce")
    set_kind("shared")
    add_headerfiles("external/stb/*.h")
    add_headerfiles("include/Lettuce/Core/*.hpp")
    add_headerfiles("include/Lettuce/Core/Compilers/*.hpp")
    add_headerfiles("include/Lettuce/Foundation/*.hpp")
    add_headerfiles("include/Lettuce/X2D/*.hpp")
    add_headerfiles("include/Lettuce/X3D/*.hpp")
    add_headerfiles("include/Lettuce/*.hpp")
    add_files("Lettuce/Core/*.cpp")
    add_files("Lettuce/Foundation/*.cpp")
    add_files("Lettuce/X3D/*.cpp")
    add_files("Lettuce/Core/Compilers/*.cpp")
    add_files("Lettuce/X3D/Geometries/*.cpp")
    -- add_files("Lettuce/X3D/Materials/*.cpp")
    add_packages("vulkansdk", "volk", "vulkan-memory-allocator", "glfw", "fastgltf")
